import os


class MatchSaveCode:
    """
    Extract python code from the code generated by LLM and save it to the specified folder
    """

    def __init__(self, target_folder, response):
        self.response = response
        self.target_folder = target_folder

    def match_code(self):
        """
        Extract python code from the code generated by LLM
        The code pattern is:
        1. The code segment starts with ```python and ends with ```
        2. The code segment contains the keywords def and return
        The code segment that meets the above two conditions is the python code we need, extract and return it, otherwise return None
        """
        try:
            completion = self.response
            if "```python" in completion:
                start_line = completion.index("```python")
                completion = completion[start_line:].strip()
                completion = completion.replace("```python", "")
                ending_line = completion.index("```")
                matched = completion[:ending_line].strip()

                def_flag = matched.find("def")
                return_flag = matched.find("return")
                if def_flag != -1 and return_flag != -1:
                    return matched
                else:
                    matched = None
                    print("match failed with no python code")
            else:
                matched = None
                print("match failed with no python code")

        except:
            print("match failed with no python code")
            matched = None

        return matched

    def save_code(self, matched_code, task_name, pyfile_name):
        """
        Save the code to the specified folder
        """

        if not os.path.exists(self.target_folder):
            os.makedirs(self.target_folder)
        file_name = os.path.join(self.target_folder, pyfile_name)

        if matched_code == None:
            with open(file_name, "w") as file:
                pass  
        else:
            print("match succeed")
            with open(file_name, "w") as file:
                file.write(matched_code)


